// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Index_副本': typeof import('./src/components/NormalInput/index_副本.vue')['default']
    InputNumber: typeof import('./src/components/NormalInput/inputNumber.vue')['default']
    NormalCheckbox: typeof import('./src/components/NormalCheckbox/index.vue')['default']
    NormalDate: typeof import('./src/components/NormalDate/index.vue')['default']
    NormalInput: typeof import('./src/components/NormalInput/index.vue')['default']
    NormalPicker: typeof import('./src/components/NormalPicker/index.vue')['default']
    NormalRadio: typeof import('./src/components/NormalRadio/index.vue')['default']
    Pagination: typeof import('./src/components/NormalTable/coms/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
