// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'Index的副本': typeof import('./src/components/NormalInput/index的副本.vue')['default']
    NormalInput: typeof import('./src/components/NormalInput/index.vue')['default']
    Pagination: typeof import('./src/components/NormalTable/coms/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
